apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service
    app: voting-app
  namespace: default
spec:
  selector:
    name: postgres-pod
    app: voting-app
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432

