apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: voting-app
  namespace: default
spec:
  selector:
    name: redis-pod
    app: voting-app
  ports:
  - name: redis
    protocol: TCP
    port: 6379
    targetPort: 6379

