apiVersion: v1
kind: Pod
metadata:
  name: "redis-pod"
  namespace: default
  labels:
    name: "redis-pod"
    app: "voting-app"
spec:
  containers:
  - name: redis
    image: redis
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort:  6379
  restartPolicy: Always
