apiVersion: v1
kind: Pod
metadata:
  name: "voting-app-pod"
  namespace: default
  labels:
    name: "voting-app-pod"
    app: "voting-app"
spec:
  containers:
  - name: voting-app
    image: kodekloud/examplevotingapp_vote:v1
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort:  80
      name:  http
  restartPolicy: Always
