apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  namespace: default
  labels:
    name: worker-app-pod
    app: voting-app
spec:
  containers:
    - name: worker-app
      image: kodekloud/examplevotingapp_worker:v1
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 200Mi
      restartPolicy: Always
