apiVersion: apps/v1
kind: Deployment
metadata:
  name:  worker-app-deploy
  namespace: default
  labels:
    name:  worker-app-deploy
    app:  voting-app
spec:
  selector:
    matchLabels:
      app: voting-app
      name: worker-app-pod
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: worker-app-pod
      namespace: default
      labels:
        name: worker-app-pod
        app: voting-app
    spec:
      containers:
      - name: worker-app
        image: kodekloud/examplevotingapp_worker:v1
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
      restartPolicy: Always

