pipeline {
    agent any
    tools {
        go 'go-1.20'
    }
    environment {
        GO111MODULE='on'
    }

    stages {
        stage('TEST') {
            steps {
                echo 'Pulling from github sample go web app code...'
                sh 'go version'
                git 'https://github.com/bindian0509/go-webapp-sample.git'
                sh 'go test ./... -v'
            }
        }
        stage('BUILD') {
            steps {
                git 'https://github.com/bindian0509/go-webapp-sample.git'
                sh 'go build .'
            }
        }
        stage('RUN') {
            steps {
                echo 'Running complied web app'
                sh 'cd /var/lib/jenkins/workspace/GoFullPipeline'
                sh 'export JENKINS_NODE_COOKIE=dontKillMe'
                sh 'export BUILD_ID=dontKillMe'
                sh 'JENKINS_NODE_COOKIE=dontKillMe nohup ./go-webapp-sample > /var/lib/jenkins/workspace/GoFullPipeline/go-app-server-nohup.out &'
                echo 'Status check....'
                sh 'curl http://localhost:8000/api/auth/loginStatus | jq'
            }
        }
    }
}
